// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = string;

export type Alignment = "start" | "center" | "end";

export type Icon = { name: string };

export type Link = { title: string | null; href: string; description: string | null };

export type Orientation = "vertical" | "horizontal";

export type Tooltip = { header: string; text: string | null; shortcut: string | null; link: Link | null };

export type Visibility = "visible" | "invisible" | "collapse";
