/* eslint-disable */
// This file was automatically generated. Do not edit this file manually.

export type ToolBarProjectCell = { menu: ContextMenu };

export type ActivityCell = {
  title: string | null;
  tooltip: Tooltip | null;
  order: Order | null;
  icon: Icon | null;
  visibility: Visibility;
  nested: ContextMenu | null;
};

export type ToolBarLeftSide = { project: ToolBarProjectCell; activities: ActivityCell[] };

export type DescribeToolBarOutput = { leftSide: ToolBarLeftSide };
