/* eslint-disable */
// This file was automatically generated. Do not edit this file manually.

export type ContextMenuCell = {
  action: Action | null;
  icon: Icon | null;
  text: string;
  shortcut: string | null;
  nested: ContextMenu | null;
};

export type ContextMenu = { content: ContextMenuCell[] };
