// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents an HTML link (`<a>`) with attributes commonly used in web development.
 */
export type HtmlLink = { href: string; target: Target | null; rel: Rel | null; text: LocalizedString | null };

/**
 * Represents possible values for the `rel` attribute in an HTML link.
 *
 * The `rel` attribute specifies the relationship between the current document
 * and the linked document.
 */
export type Rel = "noopener" | "noreferrer" | "nofollow";

/**
 * Represents possible values for the `target` attribute in an HTML link.
 *
 * The `target` attribute specifies where to open the linked document.
 */
export type Target = "_self" | "_blank" | "_parent" | "_top";
