// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppState = {
  /**
   * The user preferences for the application.
   */
  preferences: Preferences;
  defaults: Defaults;
};

export type Defaults = { theme: ThemeDescriptor; locale: LocaleDescriptor };

export type LocaleDescriptor = {
  /**
   * The language code of the locale (e.g., "en", "fr").
   */
  code: string;
  /**
   * The display name of the locale (e.g., "English", "French").
   */
  name: string;
  /**
   * The text direction of the locale, if specified ("ltr" for left-to-right, "rtl" for right-to-left).
   */
  direction?: string;
};

export type Preferences = { theme?: ThemeDescriptor; locale?: LocaleDescriptor };

export type ThemeDescriptor = {
  /**
   * Unique identifier of the theme.
   */
  id: string;
  /**
   * Display name of the theme.
   */
  name: string;
  /**
   * Source of the theme (e.g., file path or URL).
   */
  source: string;
};
