// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppStateInfo = {
  /**
   * The user preferences for the application.
   */
  preferences: PreferencesInfo;
};

export type LocaleDescriptor = {
  /**
   * The language code of the locale (e.g., "en", "fr").
   */
  code: string;
  /**
   * The display name of the locale (e.g., "English", "French").
   */
  name: string;
  /**
   * The text direction of the locale, if specified ("ltr" for left-to-right, "rtl" for right-to-left).
   */
  direction?: string;
};

export type PreferencesInfo = {
  /**
   * The selected theme for the application.
   */
  theme: ThemeDescriptor;
  /**
   * The selected locale for the application.
   */
  locale: LocaleDescriptor;
};

export type ThemeDescriptor = {
  /**
   * Unique identifier of the theme.
   */
  id: string;
  /**
   * Display name of the theme.
   */
  name: string;
  /**
   * Source of the theme (e.g., file path or URL).
   */
  source: string;
};
