// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Icon = { name: string };

export type Tooltip = { header: LocalizedString; text?: LocalizedString; shortcut?: string; link?: HtmlLink };
