// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
//
// The necessary import statements have been automatically added by a Python script.
// This ensures that all required dependencies are correctly referenced and available
// within this module.
//
// If you need to add or modify imports, please update the import_map in the script and
// re-run `make gen-models` it to regenerate the file accordingly.

import type { LocalizedString } from "@repo/moss-text";
import type { HtmlLink } from "@repo/moss-html";

export type Icon = { name: string };

export type Tooltip = { header: LocalizedString; text?: LocalizedString; shortcut?: string; link?: HtmlLink };
