// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the alignment of an element within a container.
 *
 * This enum is used to define how an element is positioned horizontally
 * or vertically relative to its container or surrounding elements.
 *
 * Variants:
 * - `Start`: Aligns the element to the start of its container (e.g., `align-items: flex-start`).
 * - `Center`: Aligns the element to the center of its container.
 * - `End`: Aligns the element to the end of its container (e.g., `align-items: flex-end`).
 */
export type Alignment = "start" | "center" | "end";

/**
 * Represents the orientation of an element or layout.
 *
 * This enum is commonly used to define whether an element or layout
 * is arranged vertically or horizontally.
 *
 * Variants:
 * - `Vertical`: The element or layout is oriented vertically.
 * - `Horizontal`: The element or layout is oriented horizontally.
 */
export type Orientation = "vertical" | "horizontal";
