// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the family of a font (e.g., Sans, Serif, Mono, or a named family).
 */
export type Family = { Name: string } | "sans" | "serif" | "mono";

/**
 * Represents a font configuration, including family, weight, and style.
 */
export type Font = {
  /**
   * The font family (e.g., Sans, Serif, Mono, or a custom name).
   */
  family: Family;
  /**
   * The weight of the font (e.g., Thin, Normal, Bold).
   */
  weight: Weight;
  /**
   * The style of the font (e.g., Italic, NotItalic).
   */
  style: Style;
};

/**
 * Represents the style of a font.
 */
export type Style = "not-italic" | "italic";

/**
 * Represents the weight of a font.
 */
export type Weight =
  | "thin"
  | "extralight"
  | "light"
  | "normal"
  | "medium"
  | "semibold"
  | "bold"
  | "extrabold"
  | "black";
