/* eslint-disable */
// This file was automatically generated. Do not edit this file manually.

export type Order = { value: number };

export type Alignment = "top" | "right" | "bottom" | "left";

export type Visibility = "visible" | "invisible" | "collapse";
