/* eslint-disable */
// This file was automatically generated. Do not edit this file manually.

export type Link = { title: string | null; href: string; description: string | null };

export type Tooltip = { header: string; text: string | null; shortcut: string | null; link: Link | null };

export type Icon = { name: string };

export type Button = { text: string };
